### ISSUE TITLE
messages EventEmitter

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/meowclient#21]
If there was an `EventEmitter` that would allow programs to listen for messages, it would be easier to handle content such as project comments.

**Comment by webdev03** [comment]
I don't think it is possible without pinging the API again and again. Programmers who use the library should be able to implement it themselves.

**Comment by hello-smile6** [comment]
> I don't think it is possible without pinging the API again and again. Programmers who use the library should be able to implement it themselves.

You could check every 5 minutes, that would be sufficient for most use-cases. (e.g. account-level anti-spam)
