### ISSUE TITLE
Project tokens

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/meowclient#23]
https://github.com/LLK/scratch-www/pull/6773#event-6664142265
Now that the token PR is merged, will it have an impact on meowclient?
@webdev03

**Comment by webdev03** [comment]
meowclient doesn't use the projects API so I don't think so. Does it impact api.scratch.mit.edu ?

**Comment by Chiroyce1** [comment]
> meowclient doesn't use the projects API so I don't think so. Does it impact api.scratch.mit.edu ?

I'm pretty sure it only affects `projects.scratch.mit.edu`, since the API doesn't show data for unshared projects anyway.
