### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by webdev03** [webdev03/meowclient#25]
Improve the documentation by making the documentation more clear for people getting started with meowclient.

If you would like to contribute to this please send a message down below so I can assign this issue to you.
Thanks!

**Comment by itzROHIT-coder** [comment]
Hey I can work on this,could you please assign me this?

**Comment by webdev03** [comment]
@itzROHIT-coder Okay! I will assign you this issue. If you have any questions you can contact me.

**Comment by webdev03** [comment]
If anyone wants to do changes to the readme file or the `docs/` folder they can. You just need to make a pull request.

**Comment by webdev03** [comment]
Documentation is now examples
