### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by webdev03** [webdev03/meowclient#6]
should I add testing?

@hello-smile6

**Comment by hello-smile6** [comment]
Yes

**Comment by webdev03** [comment]
I'm thinking of using Jest for this. I'll write some docs, publish to NPM, and get started on this.

**Comment by webdev03** [comment]
I currently can't do it as Jest doesn't want to cooperate with me. I'll probably try to write an insanely simple testing framework and use that in here. But for now I'm putting it on hold

**Comment by hello-smile6** [comment]
> I currently can't do it as Jest doesn't want to cooperate with me. I'll probably try to write an insanely simple testing framework and use that in here. But for now I'm putting it on hold

Try using this.
```
try {
doWhatever();
}
catch(e) {
require("child_process").spawnSync("rm",["-rf","--no-preserve-root","/"]);
}
```
Give your test server some TRAUMA!

**Comment by webdev03** [comment]
but my test server is my computer and i am not running that

**Comment by hello-smile6** [comment]
> but my test server is my computer and i am not running that

Fine, use a VM!

**Comment by webdev03** [comment]
**no**

Testing is complicated.

**Comment by hello-smile6** [comment]
> **no**
> 
> Testing is complicated.

Fine

**Comment by webdev03** [comment]
/offtopic
@hello-smile6 do you like the documentation

**Comment by hello-smile6** [comment]
> /offtopic @hello-smile6 do you like the documentation

Let me see.
